export interface TechnologiesType {
  IronWorking: boolean;
  Wheel: boolean;
  Paper: boolean;
  Gunpowder: boolean;
  VerticalLoom: boolean;
  SaddleAndStirrup: boolean;
  HorseCollar: boolean;
  Explosives: boolean;
  Firelance: boolean;
  Cranes: boolean;
  PromissoryNotes: boolean;
  Bombards: boolean;
  HandCannons: boolean;
  PlateArmour: boolean;
  SappersAndEngineers: boolean;
  Workshops: boolean;
  StandardizedPikes: boolean;
  Galleons: boolean;
  PrintingPress: boolean;
  Muskets: boolean;
  Limber: boolean;
  Docks: boolean;
  Gunports: boolean;
  Matchlock: boolean;
  StarForts: boolean;
  TextileManufactories: boolean;
  Reiters: boolean;
  MiningCarts: boolean;
  HumanAnatomy: boolean;
  Mortars: boolean;
  Metallurgy: boolean;
  Experimentation: boolean;
  Fluyt: boolean;
  Bayonet: boolean;
  SocketBayonet: boolean;
  Flintlock: boolean;
  FlyingShuttle: boolean;
  LeadChamberProcess: boolean;
  Gunlock: boolean;
  SteamEngine: boolean;
  PuddlingProcess: boolean;
  Rifles: boolean;
  ModernChemistry: boolean;
  CottonGin: boolean;
  SteamBoats: boolean;
  HotAirBalloon: boolean;
  PowerLoomAndSewingMachine: boolean;
  Fulminate: boolean;
  PaperMachine: boolean;
  FirstFactories: boolean;
  LinearAssemblyProcess: boolean;
  InterchangeableParts: boolean;
  CannedFood: boolean;
  Vaccines: boolean;
  Morphine: boolean;
}
;
export const technologies = {
  IronWorking: true,
  Wheel: true,
  Paper: true,
  Gunpowder: true,
  VerticalLoom: true,
  SaddleAndStirrup: true,
  HorseCollar: true,
  Explosives: true,
  Firelance: true,
  Cranes: true,
  PromissoryNotes: true,
  Bombards: true,
  HandCannons: true,
  PlateArmour: true,
  SappersAndEngineers: true,
  Workshops: true,
  StandardizedPikes: true,
  Galleons: false,
  PrintingPress: false,
  Muskets: false,
  Limber: false,
  Docks: false,
  Gunports: false,
  Matchlock: false,
  StarForts: false,
  TextileManufactories: false,
  Reiters: false,
  MiningCarts: false,
  HumanAnatomy: false,
  Mortars: false,
  Metallurgy: false,
  Experimentation: false,
  Fluyt: false,
  Bayonet: false,
  SocketBayonet: false,
  Flintlock: false,
  FlyingShuttle: false,
  LeadChamberProcess: false,
  Gunlock: false,
  SteamEngine: false,
  PuddlingProcess: false,
  Rifles: false,
  ModernChemistry: false,
  CottonGin: false,
  SteamBoats: false,
  HotAirBalloon: false,
  PowerLoomAndSewingMachine: false,
  Fulminate: false,
  PaperMachine: false,
  FirstFactories: false,
  LinearAssemblyProcess: false,
  InterchangeableParts: false,
  CannedFood: false,
  Vaccines: false,
  Morphine: false
};

