import { trimIndents } from "../string_manipulation.js";

export function generateCCFForSocialBehaviourGroups(
  socialBehaviourGroupNamePlural: string,
  socialBehaviourDistribution: Record<string, Record<string, number>>
) {
  let generatedText = ""
  Object.keys(socialBehaviourDistribution).forEach((nationKey) => {
    let total = 0.0;

    //finding the total of all socialBehaviourKey values in this nation, so we got something to divide by to find the constituencies' ratios
    Object.keys(socialBehaviourDistribution[nationKey]).forEach((socialBehaviourKey) => {
      total += socialBehaviourDistribution[nationKey][socialBehaviourKey];
    });

    //replace SocialBehaviourGroups by empty, before re-initialising every religion in it from scratch

    generatedText += trimIndents(
      `> ${nationKey}
       +> ${socialBehaviourGroupNamePlural}
       > ${socialBehaviourGroupNamePlural}
       `,
    );
    //dividing and adding to autoGeneratedCffTextField
    Object.keys(socialBehaviourDistribution[nationKey]).forEach((SocialBehaviourKey) => {
      generatedText += trimIndents(`+> ${SocialBehaviourKey}\n`);
      generatedText += trimIndents(
        `= ${(socialBehaviourDistribution[nationKey][SocialBehaviourKey] * 100) / total} ${SocialBehaviourKey}.Points\n`,
      );
    });

    generatedText += trimIndents(
      `< <
       `,
    );
  });
  return generatedText
}
