name: build-step

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: compiling typescript
        run: npx tsc
        continue-on-error: true
      - name: find differences
        run: [[ $(git status -s | wc -l) -ne 0 ]]
