name: build-step

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - run: "npm i typescript"
      - name: compiling typescript
        run: "npx tsc"
      - name: find differences
        run: "[[ $(git status -s | wc -l) -eq 0 ]]"
